[tox]
requires =
    tox>=4.2
env_list =
    py314-django{61, 60, 52}
    py313-django{61, 60, 52}
    py312-django{61, 60, 52}
    py311-django52
    py310-django52

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    -r requirements/{envname}.txt
set_env =
    PYTHONDEVMODE = 1
commands =
    python \
      -W error::ResourceWarning \
      -W error::DeprecationWarning \
      -W error::PendingDeprecationWarning \
      -m coverage run \
      -m pytest

[flake8]
max-line-length = 88
extend-ignore = E203,E501
